---
title: "Data wrangling II"
author: "Ford Holland"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(readxl)
library(viridis)
# library(p8105.datasets)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))

```

## Read in NSDUH data

```{r}

url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url)

table_marijuana = drug_use_xml %>% 
  html_nodes(css = "table") %>% 
  .[[1]] %>% 
  html_table() %>% 
  # remove 1st row to get rid of note
  slice(-1) %>% 
  as.tibble() %>% 
  janitor::clean_names()

```


## Get Harry Potter data

```{r}

hpsaga_html = 
  read_html("https://www.imdb.com/list/ls000630791/")

```

```{r}
hpsaga_html %>% 
  html_nodes(".lister-item-header a") %>% 
  html_text()
```


## Read Napolean Dynamite data

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```


## Using API

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>% 
  # extract content from output of GET command
  content("parsed")
```


## Get BRFSS data

```{r}
brfss_smart2010 = 
  GET("https://data.cdc.gov/api/views/acme-vg9e/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")
```


















